language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
    - .spago
    - output

before_install:
  - npm -g install spago

install:
  - npm install
  - npm run build
